eureka:
  client:
    serviceUrl:
      #注册表获取间隔秒
      registryFetchIntervalSeconds: 30
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    #租约续订间隔秒
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

master:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5
        maxActive: 1000
        maxOpenPreparedStatements: 20
        maxWait: 10000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 18800
        url: jdbc:mysql://192.168.1.13:3306/zhhw?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: ''
        validationQuery: SELECT 1/
        tableName: sys_datasource

spring:
  jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      open-in-view: true
      show-sql: true
#      hibernate:
#            ddl-auto: update
#            naming:
#              physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      properties:
#          multiTenancy: SCHEMA

#  security:
#       user:
#         name: admin
#         password: admin
  redis:
      database: 2
      host: 192.168.1.13
      password: ''
      port: 6379
      jedis:
        pool:
          max-active: 10
          max-wait: -1s
          min-idle: 0
          max-idle: 10

  activemq:
      broker-url: tcp://192.168.1.13:61616
      packages:
          trust-all: true
      password: admin
      user: admin
      pool:
          max-connections: 10

  jms:
      listener:
          concurrency: 10
          max-concurrency: 10
  mail:
      default-encoding: UTF-8
      host: smtp.exmail.qq.com
      password: Pan!23465
      properties:
          mail:
              smtp:
                  auth: true
                  socketFactory:
                      class: javax.net.ssl.SSLSocketFactory
                      fallback: false
                      port: 465
                  ssl:
                      enable: true
      username: notify@shencom.cn

  zipkin:
      base-url: http://localhost:9411
      enabled: true
      sender:
        type: RABBIT
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 #采样比例
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
#    virtual-host: sleuth

auth-server: http://localhost:8082
security:
  oauth2:
    client:
      client-id: scloud
      client-secret: sc23465
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
#    resource:
#      jwt:
#        key-uri: ${auth-server}/oauth/token_key
#      user-info-uri: ${auth-server}/user
#      token-info-uri: ${auth-server}/oauth/check_token

scloud:
  security:
    oauth2:
      storeType: jwt
      jwtSigningKey: iSc!scloud
      clients[0]:
        clientId: scloud
        clientSecret: sc23465
      clients[1]:
        clientId: sc123456
        clientSecret: sc123456
  oauth2:
    client:
      id: ${security.oauth2.client.resource.id}
      client-id: ${security.oauth2.client.client-id}
      client-secret: ${security.oauth2.client.client-secret}
      access-token-url: ${security.oauth2.client.access-token-uri}
      client-authentication-scheme: header
sms:
    real:
        send:
            state: 0

#service-id:
ribbon:
  ReadTimeout:  5000
  ConnectTimeout:  15000
  OkToRetryOnAllOperations: true #对所有操作请求都进行重试
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  MaxAutoRetries: 1 #对当前实例的重试次数
  compression:
    request:
      enabled: true # 配置请求GZIP压缩
      mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
      min-request-size: 2048 #配置压缩数据大小的下限
    response:
      enabled: true # 配置响应GZIP压缩

feign:
  hystrix:
    enabled: true #开启熔断器
##  client:
##    config:
##      feignName:
##        readTimeout: 10000
##        connectTimeout: 15000
hystrix:
  command:
    default: #    或者 HelloClient#hello():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
      circuitBreaker:
        requestVolumeThreshold: 10 #开启熔断触发开关
  metrics:
      enabled: true
      polling-interval-ms: 100000  #刷新间隔
      shareSecurityContext: true

log:
  path : E:\\logs
